EXEC sp_TableDesc 'prmCountry', 'Stores all world countries and their 2-digit ISO 3166-2 codes'
EXEC sp_ColumnDesc 'prmCountry', 'cnt_id', 'Country id'
EXEC sp_ColumnDesc 'prmCountry', 'cnt_name', 'Country name'
EXEC sp_ColumnDesc 'prmCountry', 'cnt_code', '2-digit ISO 3166-2 country code'

EXEC sp_TableDesc 'prmSocialNetwork', 'Social Networks that can be linked to user''s account'
EXEC sp_ColumnDesc 'prmSocialNetwork', 'socntw_id', 'Social Network id'
EXEC sp_ColumnDesc 'prmSocialNetwork', 'socntw_name', 'Social Network name'

EXEC sp_TableDesc 'tblPasswordReset', 'Stores password reset codes'
EXEC sp_ColumnDesc 'tblPasswordReset', 'pwr_email', 'Email that password was requested for'
EXEC sp_ColumnDesc 'tblPasswordReset', 'pwr_code', 'Password reset code'
EXEC sp_ColumnDesc 'tblPasswordReset', 'pwr_request_date', 'Date when password was requested'
EXEC sp_ColumnDesc 'tblPasswordReset', 'pwr_attempts', 'Number of unsuccessful attempts'

EXEC sp_TableDesc 'tblUserEmails', 'Maps email addresses to users'
EXEC sp_ColumnDesc 'tblUserEmails', 'usem_email', 'Email address'
EXEC sp_ColumnDesc 'tblUserEmails', 'usem_us_id', 'User id'
EXEC sp_ColumnDesc 'tblUserEmails', 'usem_verified', 'Indicates whether email has been verified'
EXEC sp_ColumnDesc 'tblUserEmails', 'usem_verified_date', 'Date and time when email was verified. If user registers via social network, this will be the same as registration date.'

EXEC sp_TableDesc 'tblUsers', 'Contains User Details'
EXEC sp_ColumnDesc 'tblUsers', 'us_name', 'User id'
EXEC sp_ColumnDesc 'tblUsers', 'us_name', 'Username'
EXEC sp_ColumnDesc 'tblUsers', 'us_password', 'User''s password'
EXEC sp_ColumnDesc 'tblUsers', 'us_registration_date', 'Registration date and time'
EXEC sp_ColumnDesc 'tblUsers', 'us_cnt_id', 'User''s country'
EXEC sp_ColumnDesc 'tblUsers', 'us_profile_picture', 'Profile picture''s URL'

EXEC sp_TableDesc 'tblUserSocialMedia', 'Maps users to linked social media accounts'
EXEC sp_ColumnDesc 'tblUserSocialMedia', 'ussm_us_id', 'User id'
EXEC sp_ColumnDesc 'tblUserSocialMedia', 'ussm_socntw_id', 'Social Network Id'
EXEC sp_ColumnDesc 'tblUserSocialMedia', 'ussm_usem_email', 'Email linked to user''s social network'
EXEC sp_ColumnDesc 'tblUserSocialMedia', 'ussm_socntw_user_id', 'User''s Id in the social network'