DELETE prmCountry
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (1, 'Afghanistan', 'AF');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (2, 'Albania', 'AL');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (3, 'Algeria', 'DZ');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (4, 'American Samoa', 'AS');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (5, 'Andorra', 'AD');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (6, 'Angola', 'AO');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (7, 'Anguilla', 'AI');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (8, 'Antigua and Barbuda', 'AG');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (9, 'Argentina', 'AR');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (10, 'Armenia', 'AM');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (11, 'Aruba', 'AW');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (12, 'Australia', 'AU');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (13, 'Austria', 'AT');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (14, 'Azerbaijan', 'AZ');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (15, 'Bahamas', 'BS');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (16, 'Bahrain', 'BH');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (17, 'Bangladesh', 'BD');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (18, 'Barbados', 'BB');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (19, 'Belarus', 'BY');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (20, 'Belgium', 'BE');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (21, 'Belize', 'BZ');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (22, 'Benin', 'BJ');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (23, 'Bermuda', 'BM');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (24, 'Bhutan', 'BT');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (25, 'Bolivia', 'BO');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (26, 'Bosnia and Herzegovina', 'BA');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (27, 'Botswana', 'BW');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (28, 'Brazil', 'BR');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (29, 'Brunei', 'BN');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (30, 'Bulgaria', 'BG');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (31, 'Burkina Faso', 'BF');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (32, 'Burundi', 'BI');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (33, 'Cambodia', 'KH');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (34, 'Cameroon', 'CM');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (35, 'Canada', 'CA');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (36, 'Cape Verde', 'CV');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (37, 'Cayman Islands', 'KY');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (38, 'Central African Republic', 'CF');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (39, 'Chad', 'TD');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (40, 'Chile', 'CL');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (41, 'China', 'CN');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (42, 'Colombia', 'CO');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (43, 'Comoros', 'KM');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (44, 'Congo', 'CG');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (45, 'Democratic Republic of the Congo', 'CD');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (46, 'Cook Islands', 'CK');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (47, 'Costa Rica', 'CR');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (48, 'Côte d''Ivoire', 'CI');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (49, 'Croatia', 'HR');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (50, 'Cuba', 'CU');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (51, 'Cyprus', 'CY');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (52, 'Czech Republic', 'CZ');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (53, 'Denmark', 'DK');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (54, 'Djibouti', 'DJ');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (55, 'Dominica', 'DM');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (56, 'Dominican Republic', 'DO');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (57, 'Ecuador', 'EC');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (58, 'Egypt', 'EG');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (59, 'El Salvador', 'SV');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (60, 'Equatorial Guinea', 'GQ');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (61, 'Eritrea', 'ER');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (62, 'Estonia', 'EE');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (63, 'Ethiopia', 'ET');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (64, 'Fiji', 'FJ');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (65, 'Finland', 'FI');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (66, 'France', 'FR');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (67, 'French Guiana', 'GF');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (68, 'French Polynesia', 'PF');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (69, 'Gabon', 'GA');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (70, 'Gambia', 'GM');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (71, 'Georgia', 'GE');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (72, 'Germany', 'DE');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (73, 'Ghana', 'GH');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (74, 'Greece', 'GR');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (75, 'Grenada', 'GD');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (76, 'Guam', 'GU');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (77, 'Guatemala', 'GT');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (78, 'Guinea', 'GN');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (79, 'Guinea-Bissau', 'GW');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (80, 'Guyana', 'GY');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (81, 'Haiti', 'HT');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (82, 'Honduras', 'HN');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (83, 'Hong Kong', 'HK');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (84, 'Hungary', 'HU');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (85, 'Iceland', 'IS');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (86, 'India', 'IN');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (87, 'Indonesia', 'ID');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (88, 'Iran', 'IR');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (89, 'Iraq', 'IQ');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (90, 'Ireland', 'IE');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (91, 'Israel', 'IL');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (92, 'Italy', 'IT');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (93, 'Jamaica', 'JM');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (94, 'Japan', 'JP');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (95, 'Jordan', 'JO');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (96, 'Kazakhstan', 'KZ');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (97, 'Kenya', 'KE');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (98, 'Kiribati', 'KI');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (99, 'North Korea', 'KP');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (100, 'South Korea', 'KR');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (101, 'Kuwait', 'KW');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (102, 'Kyrgyzstan', 'KG');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (103, 'Laos', 'LA');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (104, 'Latvia', 'LV');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (105, 'Lebanon', 'LB');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (106, 'Lesotho', 'LS');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (107, 'Liberia', 'LR');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (108, 'Libya', 'LY');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (109, 'Liechtenstein', 'LI');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (110, 'Lithuania', 'LT');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (111, 'Luxembourg', 'LU');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (112, 'Macao', 'MO');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (113, 'Macedonia', 'MK');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (114, 'Madagascar', 'MG');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (115, 'Malawi', 'MW');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (116, 'Malaysia', 'MY');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (117, 'Maldives', 'MV');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (118, 'Mali', 'ML');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (119, 'Malta', 'MT');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (120, 'Marshall Islands', 'MH');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (121, 'Martinique', 'MQ');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (122, 'Mauritania', 'MR');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (123, 'Mauritius', 'MU');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (124, 'Mexico', 'MX');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (125, 'Micronesia', 'FM');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (126, 'Moldova', 'MD');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (127, 'Monaco', 'MC');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (128, 'Mongolia', 'MN');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (129, 'Montenegro', 'ME');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (130, 'Montserrat', 'MS');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (131, 'Morocco', 'MA');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (132, 'Mozambique', 'MZ');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (133, 'Myanmar', 'MM');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (134, 'Namibia', 'NA');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (135, 'Nauru', 'NR');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (136, 'Nepal', 'NP');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (137, 'Netherlands', 'NL');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (138, 'New Caledonia', 'NC');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (139, 'New Zealand', 'NZ');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (140, 'Nicaragua', 'NI');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (141, 'Niger', 'NE');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (142, 'Nigeria', 'NG');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (143, 'Niue', 'NU');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (144, 'Northern Mariana', 'MP');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (145, 'Norway', 'NO');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (146, 'Oman', 'OM');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (147, 'Pakistan', 'PK');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (148, 'Palau', 'PW');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (149, 'Palestine', 'PS');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (150, 'Panama', 'PA');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (151, 'Papua New Guinea', 'PG');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (152, 'Paraguay', 'PY');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (153, 'Peru', 'PE');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (154, 'Philippines', 'PH');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (155, 'Poland', 'PL');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (156, 'Portugal', 'PT');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (157, 'Puerto Rico', 'PR');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (158, 'Qatar', 'QA');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (159, 'Romania', 'RO');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (160, 'Russia', 'RU');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (161, 'Rwanda', 'RW');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (162, 'Saint Kitts and Nevis', 'KN');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (163, 'Saint Lucia', 'LC');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (164, 'Saint Pierre and Miquelon', 'PM');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (165, 'Saint Vincent and the Grenadines', 'VC');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (166, 'Samoa', 'WS');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (167, 'San Marino', 'SM');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (168, 'Sao Tome and Principe', 'ST');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (169, 'Saudi Arabia', 'SA');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (170, 'Senegal', 'SN');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (171, 'Serbia', 'RS');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (172, 'Seychelles', 'SC');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (173, 'Sierra Leone', 'SL');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (174, 'Singapore', 'SG');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (175, 'Slovakia', 'SK');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (176, 'Slovenia', 'SI');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (177, 'Solomon Islands', 'SB');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (178, 'Somalia', 'SO');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (179, 'South Africa', 'ZA');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (180, 'Spain', 'ES');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (181, 'Sri Lanka', 'LK');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (182, 'Sudan', 'SD');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (183, 'Suriname', 'SR');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (184, 'Swaziland', 'SZ');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (185, 'Sweden', 'SE');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (186, 'Switzerland', 'CH');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (187, 'Syria', 'SY');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (188, 'Taiwan', 'TW');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (189, 'Tajikistan', 'TJ');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (190, 'Tanzania', 'TZ');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (191, 'Thailand', 'TH');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (192, 'Timor-Leste', 'TL');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (193, 'Togo', 'TG');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (194, 'Tokelau', 'TK');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (195, 'Tonga', 'TO');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (196, 'Trinidad and Tobago', 'TT');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (197, 'Tunisia', 'TN');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (198, 'Turkey', 'TR');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (199, 'Turkmenistan', 'TM');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (200, 'Turks and Caicos', 'TC');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (201, 'Tuvalu', 'TV');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (202, 'Uganda', 'UG');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (203, 'Ukraine', 'UA');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (204, 'United Arab Emirates', 'AE');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (205, 'United Kingdom', 'GB');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (206, 'United States', 'US');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (207, 'Uruguay', 'UY');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (208, 'Uzbekistan', 'UZ');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (209, 'Vanuatu', 'VU');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (210, 'Venezuela', 'VE');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (211, 'Vietnam', 'VN');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (212, 'U.S. Virgin Islands', 'VI');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (213, 'Wallis and Futuna', 'WF');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (214, 'Yemen', 'YE');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (215, 'Zambia', 'ZM');
INSERT INTO prmCountry (cnt_id, cnt_name, cnt_code) VALUES (216, 'Zimbabwe', 'ZW');

DELETE prmSocialNetwork
INSERT INTO prmSocialNetwork (socntw_id, socntw_name) VALUES (1, 'Google')
INSERT INTO prmSocialNetwork (socntw_id, socntw_name) VALUES (2, 'Facebook')
INSERT INTO prmSocialNetwork (socntw_id, socntw_name) VALUES (3, 'Twitter')